const { minify } = require('html-minifier-terser');

module.exports = async function (source) {
  return await minify(source, {
    caseSensitive: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    conservativeCollapse: true,
    html5: false,
    includeAutoGeneratedTags: false,
    keepClosingSlash: true,
    minifyCSS: true,
    minifyJS: true,
    preserveLineBreaks: true,
    removeComments: true,
  });
};
